laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('aguarde', function() {
        return view('frontend.aguarde');
    })->name('aguarde');

    Route::group([
        'middleware' => ['auth.cadastro']
    ], function() {
        // dados pessoais
        Route::get('dados-pessoais', 'HomeController@dadosPessoais')->name('dadosPessoais');
        Route::post('dados-pessoais', 'HomeController@dadosPessoaisPost')->name('dadosPessoais.post');
        Route::post('dados-pessoais/upload-comprovante/{tipo}/{grupo?}', 'HomeController@uploadComprovante')->name('uploadComprovanteDadosPessoais');

        Route::group(['middleware' => ['prePublicacaoGabarito']], function() {
            // sobre a prova
            Route::get('sobre-a-prova', 'HomeController@sobreAProva')->name('sobreAProva');

            // documentacao
            Route::get('documentacao', 'DocumentacaoController@index')->name('documentacao');
            Route::get('documentacao/documentacao-obrigatoria', 'DocumentacaoController@documentacaoObrigatoria')->name('documentacao.documentacaoObrigatoria');
            Route::get('documentacao/pendencias/documentacao-obrigatoria', 'DocumentacaoController@pendenciasDocumentacaoObrigatoria')->name('documentacao.pendencias.documentacaoObrigatoria');
            Route::post('documentacao/documentacao-obrigatoria', 'DocumentacaoController@documentacaoObrigatoriaPost')->name('documentacao.documentacaoObrigatoriaPost');
            Route::post('documentacao/pendencias/documentacao-obrigatoria', 'DocumentacaoController@pendenciasDocumentacaoObrigatoriaPost')->name('documentacao.pendencias.documentacaoObrigatoriaPost');
            Route::get('documentacao/especializacao-em-cardiologia', 'DocumentacaoController@especializacaoEmCardiologia')->name('documentacao.especializacaoEmCardiologia');
            Route::get('documentacao/pendencias/especializacao-em-cardiologia', 'DocumentacaoController@pendenciasEspecializacaoEmCardiologia')->name('documentacao.pendencias.especializacaoEmCardiologia');
            Route::post('documentacao/especializacao-em-cardiologia', 'DocumentacaoController@especializacaoEmCardiologiaPost')->name('documentacao.especializacaoEmCardiologiaPost');
            Route::post('documentacao/pendencias/especializacao-em-cardiologia', 'DocumentacaoController@pendenciasEspecializacaoEmCardiologiaPost')->name('documentacao.pendencias.especializacaoEmCardiologiaPost');
            Route::get('documentacao/documentos-facultativos', 'DocumentacaoController@documentosFacultativos')->name('documentacao.documentosFacultativos');
            Route::get('documentacao/pendencias/documentos-facultativos', 'DocumentacaoController@pendenciasDocumentosFacultativos')->name('documentacao.pendencias.documentosFacultativos');
            Route::post('documentacao/documentos-facultativos', 'DocumentacaoController@documentosFacultativosPost')->name('documentacao.documentosFacultativosPost');
            Route::post('documentacao/pendencias/documentos-facultativos', 'DocumentacaoController@pendenciasDocumentosFacultativosPost')->name('documentacao.pendencias.documentosFacultativosPost');
            Route::get('documentacao/declaracoes-finais', 'DocumentacaoController@declaracoesFinais')->name('documentacao.declaracoesFinais');
            Route::get('documentacao/pendencias/declaracoes-finais', 'DocumentacaoController@pendenciasDeclaracoesFinais')->name('documentacao.pendencias.declaracoesFinais');
            Route::post('documentacao/declaracoes-finais', 'DocumentacaoController@declaracoesFinaisPost')->name('documentacao.declaracoesFinaisPost');
            Route::post('documentacao/pendencias/declaracoes-finais', 'DocumentacaoController@pendenciasDeclaracoesFinaisPost')->name('documentacao.pendencias.declaracoesFinaisPost');
            Route::post('documentacao/upload-comprovante/{input}/{grupo?}', 'DocumentacaoController@uploadComprovante')->name('documentacao.uploadComprovante');
            Route::post('documentacao/upload-comprovante-substituicao/{input}/{grupo?}', 'DocumentacaoController@uploadComprovanteSubstituicao')->name('documentacao.uploadComprovanteSubstituicao');
            Route::get('documentacao/enviar-documentacao', 'DocumentacaoController@enviarDocumentacao')->name('documentacao.enviarDocumentacao');
            Route::get('documentacao/enviar-pendencias', 'DocumentacaoController@enviarPendencias')->name('documentacao.enviarPendencias');
            Route::get('envio', 'DocumentacaoController@envio')->name('envio');

            // revisao
            Route::post('documentacao/solicitacao-de-revisao', 'DocumentacaoController@revisaoPost')->name('documentacao.revisaoPost');

            // pagamento
            Route::get('pagamento', 'PagamentoController@index')->name('pagamento');

            // voucher
            Route::get('voucher', 'HomeController@voucher')->name('voucher');

            // carta de confirmação
            Route::get('carta-de-confirmacao', 'HomeController@cartaDeConfirmacao')->name('cartaDeConfirmacao');
        });

        Route::group(['middleware' => ['informacoes']], function() {
            Route::get('informacoes', 'InformacoesController@index')->name('informacoes');
            Route::post('recursos', 'RecursosController@store')->name('recursos.store');
            Route::get('recursos/{id}', 'RecursosController@show')->name('recursos.show');
            Route::post('recursos/{id}/enviar', 'RecursosController@enviar')->name('recursos.enviar');
            Route::post('recursos/upload-comprovante/{input}', 'RecursosController@uploadComprovante')->name('recursos.uploadComprovante');
            Route::get('declaracao-de-aprovacao', 'InformacoesController@declaracaoDeAprovacao')->name('declaracaoDeAprovacao');
        });
    });

    // Cadastro
    Route::get('login', 'HomeController@login')->name('cadastro.login');
    Route::get('logout', 'CadastroAuth\AuthController@logout')->name('cadastro.logout');
    Route::get('esqueci-minha-senha', 'HomeController@esqueci')->name('cadastro.esqueci');
    Route::get('redefinicao-de-senha/{token}', 'CadastroAuth\PasswordController@showResetForm');
    Route::post('cadastro', 'CadastroAuth\AuthController@create')->name('cadastro.cadastroPost');
    Route::post('login', 'CadastroAuth\AuthController@login')->name('cadastro.loginPost');
    Route::post('redefinicao-de-senha', 'CadastroAuth\PasswordController@sendResetLinkEmail')->name('cadastro.redefinicao');
    Route::post('redefinir-senha', 'CadastroAuth\PasswordController@reset')->name('cadastro.redefinir');

    // Administração
    Route::group([
        'middleware' => ['auth.admin'],
        'prefix'     => 'admin'
    ], function() {
        Route::get('/', 'AdminController@index')->name('admin');
        Route::get('busca', 'AdminController@busca')->name('admin.busca');
        Route::get('novas-inscricoes', 'AdminController@novasInscricoes')->name('admin.novasInscricoes');
        Route::get('nao-enviadas', 'AdminController@naoEnviadas')->name('admin.naoEnviadas');
        Route::get('validacoes-em-andamento', 'AdminController@validacoesEmAndamento')->name('admin.validacoesEmAndamento');
        Route::get('substituicoes-solicitadas', 'AdminController@substituicoesSolicitadas')->name('admin.substituicoesSolicitadas');
        Route::get('substituicoes-recebidas', 'AdminController@substituicoesRecebidas')->name('admin.substituicoesRecebidas');
        Route::get('inscricoes-validadas', 'AdminController@inscricoesValidadas')->name('admin.inscricoesValidadas');
        Route::get('inscricoes-validadas/extrair', 'AdminController@inscricoesValidadasExtrair')->name('admin.inscricoesValidadas.extrair');
        Route::get('inscricoes-invalidadas', 'AdminController@inscricoesInvalidadas')->name('admin.inscricoesInvalidadas');
        Route::get('solicitacoes-de-revisao', 'AdminController@solicitacoesDeRevisao')->name('admin.solicitacoesDeRevisao');
        Route::get('inscricao/{id}/concluir-revisao', 'AdminController@concluirRevisao')->name('admin.concluirRevisao');
        Route::get('inscricao/{id}/validar', 'AdminController@inscricaoValidar')->name('admin.inscricao.validar');
        Route::get('inscricao/{id}/invalidar', 'AdminController@inscricaoInvalidar')->name('admin.inscricao.invalidar');
        Route::get('inscricao/{id}/solicitar-substituicoes', 'AdminController@inscricaoSolicitarSubstituicoes')->name('admin.inscricao.solicitarSubstituicoes');
        Route::get('inscricao/{id}/{secao?}', 'AdminController@inscricao')->name('admin.inscricao');
        Route::get('inscricao/{id}/comprovante/validar/{comprovante}/{grupo?}', 'AdminController@comprovanteValidar')->name('admin.comprovante.validar');
        Route::get('inscricao/{id}/comprovante/invalidar/{comprovante}/{grupo?}', 'AdminController@comprovanteInvalidar')->name('admin.comprovante.invalidar');
        Route::post('inscricao/{id}/comprovante/solicitar-substituicao/{comprovante}/{grupo?}', 'AdminController@comprovanteSolicitarSubstituicao')->name('admin.comprovante.solicitarSubstituicao');
        Route::get('inscricao/{id}/comprovante/{comprovante}/{grupo?}', 'AdminController@comprovante')->name('admin.comprovante');
        Route::post('inscricao/{id}/liberar', 'AdminController@liberarInscricao')->name('admin.inscricao.liberar');

        Route::get('recursos', 'AdminController@recursos')->name('admin.recursos');
        Route::get('recursos/extrair', 'AdminController@recursosExtrair')->name('admin.recursos.extrair');
        Route::get('recursos/extrair-emails', 'AdminController@recursosExtrairEmails')->name('admin.recursos.extrairEmails');
        Route::get('recursos/{id}', 'AdminController@recursosShow')->name('admin.recursos.show');
        Route::get('recursos/exibir/{boolean}', 'AdminController@recursosExibir')->name('admin.recursos.exibir');

laravel/app/Models/Recurso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Recurso extends Model
{
    protected $table = 'recursos';

    protected $guarded = ['id'];

    public static function boot()
    {
        parent::boot();

        self::created(function($model) {
            $model->protocolo = self::geraProtocolo($model);
            $model->questao_matriz = $model->questao;
            $model->save();

            // se não houver a questão matriz na tabela de respostas
            // cria uma linha com a resposta em branco
            if (! RecursoResposta::where('questao_matriz', $model->questao_matriz)->count()) {
                RecursoResposta::create([
                    'questao_matriz' => $model->questao_matriz,
                    'resposta'       => ''
                ]);
            }
        });
    }

    public function cadastro()
    {
        return $this->belongsTo(Cadastro::class, 'cadastro_id');
    }

    private static function geraProtocolo($recurso)
    {
        return 'R' . $recurso->cadastro->id . sprintf("%03d", $recurso->id);
    }

    public function getQuestaoBlocoAttribute()
    {
        $questao = $this->questao_matriz;

        if ($questao <= 50) {
            return $questao.' - bloco 1';
        }

        return ($questao - 50).' - bloco 2';
    }

    public static function selectQuestao()
    {
        $options = [];

        foreach (range(1, 100) as $i) {
            if ($i <= 50) {
                $options[$i] = 'questão '.$i.' - bloco 1';
            } else {
                $options[$i] = 'questão '.($i - 50).' - bloco 2';
            }
        }

        return $options;
    }

    private static function questaoMatriz($prova, $questao)
    {
        if (! in_array($prova, ['A', 'B', 'C', 'D']) || ! in_array($questao, range(1, 120))) {
            return 0;
        }

        $matriz = [
            'A' => range(1, 120),
            'B' => array_merge(
                range(31, 60),
                range(1, 30),
                range(91, 120),
                range(61, 90)
            ),
            'C' => array_merge(
                range(61, 120),
                range(1, 60)
            ),
            'D' => array_merge(
                range(91, 120),
                range(61, 90),
                range(31, 60),
                range(1, 30)
            ),
        ];

        return $matriz[$prova][$questao - 1];
    }
}

laravel/app/Http/Controllers/InformacoesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Helpers\Tools;

use App\Models\RespostaGeralRecursos;
use App\Models\RecursoResposta;

class InformacoesController extends Controller
{
    public function index()
    {
        $cadastro      = auth('cadastro')->user();
        $recursos      = $cadastro->recursos;
        $respostas     = RecursoResposta::lists('resposta', 'questao_matriz');
        $respostaGeral = RespostaGeralRecursos::first();

        $periodoRecurso = Tools::periodoRecurso();

        return view('frontend.informacoes.index', compact('cadastro', 'recursos', 'respostas', 'respostaGeral', 'periodoRecurso'));
    }

    public function declaracaoDeAprovacao()
    {
        $cadastro = auth('cadastro')->user();

        if ($cadastro->status_avaliacao != 'aprovado') {
            abort('404');
        }

        return view('frontend.informacoes.declaracao-de-aprovacao', compact('cadastro'));
    }
}

laravel/resources/views/frontend/informacoes/cadastro-invalido.blade.php
@extends('frontend.common.template')

@section('content')

    @include('frontend.common._main-nav')

    <div class="pag-informacoes interna center">
        <div class="main-box">
            <h2>Informações Sobre a Prova</h2>
            <p>O período de inscrições para a Prova Tec 2020 já foi encerrado. Para dúvidas consulte o edital.</p>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/informacoes/declaracao-de-aprovacao.blade.php
@extends('frontend.common.template')

@section('content')

    @include('frontend.common._main-nav')

    <div class="voucher interna center">
        <div class="main-box" style="text-align:center">
            <h2>DECLARAÇÃO DE APROVAÇÃO</h2>
            <img src="{{ asset('assets/img/layout/marcas-voucher.png') }}" alt="" style="margin-bottom:2.5em">
            <p><strong>TEC/2020</strong></p>
            <p>Rio de Janeiro, {{ Tools::dataExtenso(\Carbon\Carbon::now()->format('d/m/Y')) }}.</p>
            <p>
                A SOCIEDADE BRASILEIRA DE CARDIOLOGIA declara para os devidos fins que {{ $cadastro->nome }} – CPF {{ $cadastro->cpf }}, obteve o Título de Especialista em Cardiologia, por meio de prova realizada em 20/12/2020 de acordo com as Normas estabelecidas pela Associação Médica Brasileira.
            </p>
            <p>
                Ressaltamos que o prazo para entrega do Diploma pela AMB é de aproximadamente 120 dias, a contar da data do pagamento do boleto.
            </p>
            <img src="{{ asset('assets/img/layout/assinatura-marcus.png') }}" alt="" style="width: 260px; margin:3em auto 1em">
            <p>
                <strong>Marcus Vinícius Santos Andrade</strong><br>
                Coordenador do CJTEC/SBC
            </p>
        </div>
        <p></p>
        <a href="javascript:window.print()">imprimir &raquo;</a>
    </div>

@endsection

laravel/resources/views/frontend/informacoes/solicitacao-de-recurso.blade.php
@extends('frontend.common.template')

@section('content')

    @include('frontend.common._main-nav')

    <div class="voucher interna center">
        <div class="main-box">
            <h2>SOLICITAÇÃO DE RECURSO</h2>
            <img src="{{ asset('assets/img/layout/marcas-voucher.png') }}" alt="">
            <div class="inscricao">
                protocolo: <span>{{ $recurso->protocolo }}</span><br>
                <span style="display:block;font-size:14px;font-weight:normal;margin-top:8px">
                    Registrado em: <strong>{{ Tools::formataDataHorario($recurso->created_at) }}</strong>
                </span>
                <span style="display:block;font-size:15px;font-weight:normal">
                    Recurso impetrado para a questão <strong>{{ $recurso->questao_bloco }}</strong> da prova <strong>{{ $recurso->prova }}</strong>
                </span>
            </div>
            <p><small>
                Justificativa:<br>
                {!! nl2br($recurso->justificativa) !!}
            </small></p>
            <p><small>
                Bibliografia:<br>
                {!! nl2br($recurso->bibliografia) !!}
            </small></p>
            <p style="margin-top:2em">Data: _____/_____/_____</p>
            <p style="margin-top:1.5em">Assinatura: ______________________________________________</p>
        </div>

        <p class="observacao">
            Observação: Reconhecer firma e <strong>enviar via Sistema do Provatec</strong> (www.provatec.com.br) até dia 23 de Dezembro de 2020.<br>
            A simples impressão deste documento <strong>NÃO CONFIGURA O ENVIO DO RECURSO.</strong>
        </p>
        <a href="javascript:window.print()">imprimir &raquo;</a>
    </div>

@endsection